name: rental_dispose_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.6 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  country_code_picker: ^3.0.0
  intl_phone_field: ^3.2.0
  carousel_slider: ^4.2.1
  libphonenumber: ^2.0.2
  google_fonts: ^5.1.0
  font_awesome_flutter: ^10.4.0
  flutter_slidable: ^3.0.0
  user_profile_avatar: ^0.1.2
  dotted_border: ^2.0.0+3
  shared_preferences: ^2.2.0
  image_picker: ^1.0.2
  image_cropper: ^5.0.0
  flutter_image_compress: ^2.0.4

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/

